# LICENSE HEADER MANAGED BY add-license-header
#
# Copyright (c) 2026 EurekAI Pvt. Ltd.
# SPDX-License-Identifier: MIT
#

"""auto

Revision ID: e85bffa931ca
Revises:
Create Date: 2026-09-06 19:05:16.847685

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e85bffa931ca"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploaded_files",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=False),
        sa.Column("file_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "scan_res", sa.String(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("scan_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('profile_pic', 'note_img', 'comment_img', 'post_img', 'attachment')"
        ),
        sa.CheckConstraint(
            "scan_res IN ('pending', 'clean', 'suspicious', 'malicious', 'failed')",
            name="ck_uploaded_file_scan_res",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket", "key", name="uq_bucket_key"),
    )
    op.create_index(
        op.f("ix_uploaded_files_id"), "uploaded_files", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_uploaded_files_user_id"), "uploaded_files", ["user_id"], unique=False
    )
    op.create_table(
        "sanitized_files",
        sa.Column("uploaded_file_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=False),
        sa.Column("file_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "scan_res", sa.String(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("scan_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_file_id"], ["uploaded_files.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket", "key", name="uq_bucket_key_sanitized"),
    )
    op.create_index(
        op.f("ix_sanitized_files_id"), "sanitized_files", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_sanitized_files_uploaded_file_id"),
        "sanitized_files",
        ["uploaded_file_id"],
        unique=True,
    )
    op.create_table(
        "upload_jobs",
        sa.Column("uploaded_file_id", sa.UUID(), nullable=False),
        sa.Column("celery_task_id", sa.String(), nullable=True),
        sa.Column(
            "status", sa.String(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "stage", sa.String(), server_default=sa.text("'download'"), nullable=False
        ),
        sa.Column("retries", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage IN ('download', 'scan', 'sanitize', 'post_scan', 'upload', 'cleanup')",
            name="ck_upload_job_stage",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'retrying', 'failed', 'complete', 'rejected')",
            name="ck_upload_job_status",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_file_id"],
            ["uploaded_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_upload_jobs_id"), "upload_jobs", ["id"], unique=False)
    op.create_index(
        "ix_upload_jobs_retry", "upload_jobs", ["status", "next_retry_at"], unique=False
    )
    op.create_index(
        op.f("ix_upload_jobs_uploaded_file_id"),
        "upload_jobs",
        ["uploaded_file_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_upload_jobs_uploaded_file_id"), table_name="upload_jobs")
    op.drop_index("ix_upload_jobs_retry", table_name="upload_jobs")
    op.drop_index(op.f("ix_upload_jobs_id"), table_name="upload_jobs")
    op.drop_table("upload_jobs")
    op.drop_index(
        op.f("ix_sanitized_files_uploaded_file_id"), table_name="sanitized_files"
    )
    op.drop_index(op.f("ix_sanitized_files_id"), table_name="sanitized_files")
    op.drop_table("sanitized_files")
    op.drop_index(op.f("ix_uploaded_files_user_id"), table_name="uploaded_files")
    op.drop_index(op.f("ix_uploaded_files_id"), table_name="uploaded_files")
    op.drop_table("uploaded_files")
    # ### end Alembic commands ###
